// Complete Tarot Card Database with meanings from A.E. Waite's Pictorial Key to the Tarot
// Images from public domain Rider-Waite-Smith deck

export interface TarotCardData {
  id: string;
  name: string;
  name_pt: string;
  number: number;
  arcana: 'major' | 'minor';
  suit?: string;
  element?: string;
  keywords: string[];
  keywords_pt: string[];
  meaning_up: string;
  meaning_up_pt: string;
  meaning_rev: string;
  meaning_rev_pt: string;
  description: string;
  love: string;
  career: string;
  advice: string;
  imageUrl: string;
}

// Base URL for Rider-Waite images (public domain)
const IMG_BASE = "https://www.sacred-texts.com/tarot/pkt/img";

// Alternative high-quality image sources
const IMG_SOURCES = {
  wikimedia: "https://upload.wikimedia.org/wikipedia/commons/thumb",
  // Fallback placeholder
  placeholder: "https://placehold.co/300x520/1c1022/9311d4?text="
};

export const TAROT_CARDS: TarotCardData[] = [
  // ========== MAJOR ARCANA ==========
  {
    id: "maj_0",
    name: "The Fool",
    name_pt: "O Louco",
    number: 0,
    arcana: "major",
    element: "Air",
    keywords: ["Freedom", "Faith", "Innocence", "New Beginnings"],
    keywords_pt: ["Liberdade", "Fé", "Inocência", "Novos Começos"],
    meaning_up: "New beginnings, innocence, spontaneity, a free spirit. Taking a leap of faith into the unknown with optimism and trust.",
    meaning_up_pt: "Novos começos, inocência, espontaneidade, espírito livre. Dar um salto de fé no desconhecido com otimismo e confiança.",
    meaning_rev: "Holding back, recklessness, risk-taking without thought. Naivety leading to poor decisions.",
    meaning_rev_pt: "Hesitação, imprudência, assumir riscos sem pensar. Ingenuidade levando a decisões ruins.",
    description: "A young man stands at the edge of a cliff, about to step into the unknown. He carries a small bag and a white rose, symbolizing purity. A small dog at his feet represents loyalty and protection.",
    love: "A new romance is on the horizon. Be open to unexpected connections. If in a relationship, bring back spontaneity and adventure.",
    career: "Time for a new career path or project. Don't overthink - trust your instincts and take that leap.",
    advice: "Embrace the unknown with an open heart. Sometimes the best adventures begin with a single step into uncertainty.",
    imageUrl: `${IMG_BASE}/ar00.jpg`
  },
  {
    id: "maj_1",
    name: "The Magician",
    name_pt: "O Mago",
    number: 1,
    arcana: "major",
    element: "Air",
    keywords: ["Manifestation", "Power", "Action", "Resourcefulness"],
    keywords_pt: ["Manifestação", "Poder", "Ação", "Desenvoltura"],
    meaning_up: "Skill, diplomacy, willpower, self-confidence. You have all the tools you need to manifest your desires. Take action now.",
    meaning_up_pt: "Habilidade, diplomacia, força de vontade, autoconfiança. Você tem todas as ferramentas necessárias para manifestar seus desejos.",
    meaning_rev: "Manipulation, poor planning, untapped talents. Using skills for deception or not using them at all.",
    meaning_rev_pt: "Manipulação, planejamento ruim, talentos não utilizados. Usar habilidades para enganar ou não usá-las.",
    description: "A figure stands with one hand pointing to the sky and one to the earth, channeling divine energy. On his table are the symbols of all four suits - representing mastery over all elements.",
    love: "Take initiative in love. You have the charm and ability to attract what you desire. Be authentic.",
    career: "You have everything needed for success. Use your skills and willpower to achieve your goals. Great potential ahead.",
    advice: "You have the resources you need. Channel your energy and act now with confidence.",
    imageUrl: `${IMG_BASE}/ar01.jpg`
  },
  {
    id: "maj_2",
    name: "The High Priestess",
    name_pt: "A Sacerdotisa",
    number: 2,
    arcana: "major",
    element: "Water",
    keywords: ["Intuition", "Mystery", "Inner Knowledge", "Subconscious"],
    keywords_pt: ["Intuição", "Mistério", "Conhecimento Interior", "Subconsciente"],
    meaning_up: "Secrets, mystery, intuition, wisdom. The answers you seek are within. Trust your inner voice and look beyond the surface.",
    meaning_up_pt: "Segredos, mistério, intuição, sabedoria. As respostas que você busca estão dentro de você. Confie em sua voz interior.",
    meaning_rev: "Secrets revealed, disconnection from intuition, superficial knowledge. Ignoring your inner wisdom.",
    meaning_rev_pt: "Segredos revelados, desconexão da intuição, conhecimento superficial. Ignorar sua sabedoria interior.",
    description: "A serene woman sits between two pillars - one black, one white - representing duality. She holds a scroll of esoteric knowledge, partially hidden by her cloak.",
    love: "Listen to your intuition about relationships. There may be hidden aspects to explore. Trust your gut feelings.",
    career: "Hidden information may come to light. Use your intuition in decisions. Research and reflect before acting.",
    advice: "Be still and listen to your inner voice. The answers are already within you - you just need to quiet the noise to hear them.",
    imageUrl: `${IMG_BASE}/ar02.jpg`
  },
  {
    id: "maj_3",
    name: "The Empress",
    name_pt: "A Imperatriz",
    number: 3,
    arcana: "major",
    element: "Earth",
    keywords: ["Fertility", "Abundance", "Nature", "Nurturing"],
    keywords_pt: ["Fertilidade", "Abundância", "Natureza", "Nutrição"],
    meaning_up: "Fruitfulness, action, abundance, creativity. A time of growth, nurturing, and bringing ideas to fruition.",
    meaning_up_pt: "Fertilidade, ação, abundância, criatividade. Um momento de crescimento, nutrição e realização de ideias.",
    meaning_rev: "Creative block, dependence on others, neglecting self-care. Smothering or being smothered.",
    meaning_rev_pt: "Bloqueio criativo, dependência dos outros, negligência do autocuidado. Sufocar ou ser sufocado.",
    description: "A regal woman sits in a lush garden, surrounded by nature's bounty. She wears a crown of stars and holds a scepter, representing her connection to earth and sky.",
    love: "Love flourishes. Fertility, sensuality, and deep emotional connection. A nurturing relationship.",
    career: "Creative projects thrive. Abundance in work. Good time to start businesses or grow existing ones.",
    advice: "Connect with nature and your creative side. Nurture yourself and your projects - abundance will follow.",
    imageUrl: `${IMG_BASE}/ar03.jpg`
  },
  {
    id: "maj_4",
    name: "The Emperor",
    name_pt: "O Imperador",
    number: 4,
    arcana: "major",
    element: "Fire",
    keywords: ["Authority", "Structure", "Leadership", "Stability"],
    keywords_pt: ["Autoridade", "Estrutura", "Liderança", "Estabilidade"],
    meaning_up: "Stability, power, protection, authority. Structure and discipline lead to achievement. Take control of your situation.",
    meaning_up_pt: "Estabilidade, poder, proteção, autoridade. Estrutura e disciplina levam à realização. Assuma o controle da sua situação.",
    meaning_rev: "Tyranny, rigidity, coldness. Abuse of power or lack of discipline. Being too controlling or too passive.",
    meaning_rev_pt: "Tirania, rigidez, frieza. Abuso de poder ou falta de disciplina. Ser muito controlador ou muito passivo.",
    description: "A powerful ruler sits on a stone throne adorned with ram heads, symbolizing Aries. He holds an ankh scepter and an orb, representing life and worldly power.",
    love: "A stable, committed relationship. May indicate a protective partner. Balance authority with compassion.",
    career: "Leadership opportunities. Time to establish structure and take charge. Success through discipline.",
    advice: "Create order from chaos. Set clear boundaries and stick to them. Lead with wisdom, not just power.",
    imageUrl: `${IMG_BASE}/ar04.jpg`
  },
  {
    id: "maj_5",
    name: "The Hierophant",
    name_pt: "O Hierofante",
    number: 5,
    arcana: "major",
    element: "Earth",
    keywords: ["Tradition", "Conformity", "Institutions", "Spiritual Wisdom"],
    keywords_pt: ["Tradição", "Conformidade", "Instituições", "Sabedoria Espiritual"],
    meaning_up: "Spiritual wisdom, religious beliefs, tradition, conformity. Seeking guidance from established institutions or mentors.",
    meaning_up_pt: "Sabedoria espiritual, crenças religiosas, tradição, conformidade. Buscar orientação de instituições estabelecidas ou mentores.",
    meaning_rev: "Personal beliefs, freedom, challenging the status quo. Breaking from tradition.",
    meaning_rev_pt: "Crenças pessoais, liberdade, desafiar o status quo. Romper com a tradição.",
    description: "A religious figure sits between two pillars, blessing two followers. He wears a triple crown and holds a papal cross, representing his spiritual authority.",
    love: "Traditional relationship values. May indicate marriage or commitment. Shared beliefs strengthen bonds.",
    career: "Following established paths leads to success. Seek mentorship. Education and credentials matter.",
    advice: "Consider what traditions serve you and which hold you back. Seek wisdom from teachers, but form your own beliefs.",
    imageUrl: `${IMG_BASE}/ar05.jpg`
  },
  {
    id: "maj_6",
    name: "The Lovers",
    name_pt: "Os Amantes",
    number: 6,
    arcana: "major",
    element: "Air",
    keywords: ["Love", "Harmony", "Choices", "Alignment"],
    keywords_pt: ["Amor", "Harmonia", "Escolhas", "Alinhamento"],
    meaning_up: "Love, harmony, relationships, choices. A union of opposites. Important decisions that align with your values.",
    meaning_up_pt: "Amor, harmonia, relacionamentos, escolhas. Uma união de opostos. Decisões importantes alinhadas com seus valores.",
    meaning_rev: "Disharmony, imbalance, misalignment. Relationship conflicts or poor choices.",
    meaning_rev_pt: "Desarmonia, desequilíbrio, desalinhamento. Conflitos de relacionamento ou escolhas ruins.",
    description: "A man and woman stand beneath an angel, representing divine blessing. The Tree of Knowledge and Tree of Life appear behind them, symbolizing the choice between temptation and paradise.",
    love: "Deep soul connection. True love and partnership. A significant relationship choice may arise.",
    career: "Partnerships and collaborations thrive. Choose work that aligns with your values.",
    advice: "Follow your heart but use your head. Make choices that honor both your desires and your integrity.",
    imageUrl: `${IMG_BASE}/ar06.jpg`
  },
  {
    id: "maj_7",
    name: "The Chariot",
    name_pt: "O Carro",
    number: 7,
    arcana: "major",
    element: "Water",
    keywords: ["Willpower", "Determination", "Victory", "Control"],
    keywords_pt: ["Força de Vontade", "Determinação", "Vitória", "Controle"],
    meaning_up: "Victory, willpower, determination, success through control. Overcoming obstacles through focused action.",
    meaning_up_pt: "Vitória, força de vontade, determinação, sucesso através do controle. Superar obstáculos através de ação focada.",
    meaning_rev: "Lack of control, aggression, obstacles. Being pulled in different directions.",
    meaning_rev_pt: "Falta de controle, agressão, obstáculos. Ser puxado em diferentes direções.",
    description: "A warrior stands in a chariot drawn by two sphinxes - one black, one white. He wears armor decorated with moons and stars, wielding willpower rather than reins to guide his path.",
    love: "Take charge of your love life. Pursue what you want with confidence. Balance emotions with action.",
    career: "Victory through determination. Stay focused on goals despite obstacles. Success is within reach.",
    advice: "Harness your inner strength and focus your will. You can overcome any obstacle with determination and balance.",
    imageUrl: `${IMG_BASE}/ar07.jpg`
  },
  {
    id: "maj_8",
    name: "Strength",
    name_pt: "A Força",
    number: 8,
    arcana: "major",
    element: "Fire",
    keywords: ["Courage", "Patience", "Inner Strength", "Compassion"],
    keywords_pt: ["Coragem", "Paciência", "Força Interior", "Compaixão"],
    meaning_up: "Inner strength, courage, patience, compassion. Taming the beast within through gentle power, not brute force.",
    meaning_up_pt: "Força interior, coragem, paciência, compaixão. Domar a fera interior através de poder gentil, não força bruta.",
    meaning_rev: "Self-doubt, weakness, insecurity. Raw emotions overwhelming reason.",
    meaning_rev_pt: "Auto-dúvida, fraqueza, insegurança. Emoções brutas dominando a razão.",
    description: "A woman gently holds open the jaws of a lion, showing mastery over primal forces through love rather than violence. The infinity symbol hovers above her head.",
    love: "Patience and compassion strengthen relationships. Face challenges with gentle strength.",
    career: "Perseverance leads to success. Handle difficult situations with grace and confidence.",
    advice: "True strength comes from within - from patience, compassion, and self-mastery. Face your fears with a gentle heart.",
    imageUrl: `${IMG_BASE}/ar08.jpg`
  },
  {
    id: "maj_9",
    name: "The Hermit",
    name_pt: "O Eremita",
    number: 9,
    arcana: "major",
    element: "Earth",
    keywords: ["Introspection", "Solitude", "Guidance", "Inner Wisdom"],
    keywords_pt: ["Introspecção", "Solidão", "Orientação", "Sabedoria Interior"],
    meaning_up: "Soul-searching, introspection, solitude, inner guidance. Time to withdraw and reflect on your path.",
    meaning_up_pt: "Busca interior, introspecção, solidão, orientação interior. Hora de se retirar e refletir sobre seu caminho.",
    meaning_rev: "Isolation, loneliness, withdrawal. Refusing guidance or being lost in darkness.",
    meaning_rev_pt: "Isolamento, solidão, afastamento. Recusar orientação ou estar perdido na escuridão.",
    description: "An old man stands alone on a mountain peak, holding a lantern with a six-pointed star. His staff represents knowledge gained through experience.",
    love: "Time for self-reflection about what you truly want in love. Solitude can bring clarity.",
    career: "Step back and assess your path. Seek wise counsel. Sometimes withdrawal leads to breakthrough.",
    advice: "Take time for solitude and reflection. The light of wisdom shines brightest in the quiet of your own soul.",
    imageUrl: `${IMG_BASE}/ar09.jpg`
  },
  {
    id: "maj_10",
    name: "Wheel of Fortune",
    name_pt: "A Roda da Fortuna",
    number: 10,
    arcana: "major",
    element: "Fire",
    keywords: ["Cycles", "Destiny", "Luck", "Change"],
    keywords_pt: ["Ciclos", "Destino", "Sorte", "Mudança"],
    meaning_up: "Destiny, turning point, good luck, cycles of life. What goes around comes around. Embrace change.",
    meaning_up_pt: "Destino, ponto de virada, boa sorte, ciclos da vida. O que vai, volta. Abrace a mudança.",
    meaning_rev: "Bad luck, resistance to change, breaking cycles. Fighting against the natural flow.",
    meaning_rev_pt: "Má sorte, resistência à mudança, quebrar ciclos. Lutar contra o fluxo natural.",
    description: "A great wheel turns, with mythical creatures ascending and descending. The sphinx sits atop, representing wisdom amid constant change.",
    love: "A turning point in love. Fate may bring unexpected connections or changes.",
    career: "Change is coming - likely positive. Ride the wave of opportunity. Luck favors the prepared.",
    advice: "Life moves in cycles. Accept that change is constant and position yourself to benefit from the turning wheel.",
    imageUrl: `${IMG_BASE}/ar10.jpg`
  },
  {
    id: "maj_11",
    name: "Justice",
    name_pt: "A Justiça",
    number: 11,
    arcana: "major",
    element: "Air",
    keywords: ["Fairness", "Truth", "Cause and Effect", "Law"],
    keywords_pt: ["Justiça", "Verdade", "Causa e Efeito", "Lei"],
    meaning_up: "Justice, fairness, truth, cause and effect. Decisions must be made with logic and impartiality.",
    meaning_up_pt: "Justiça, equidade, verdade, causa e efeito. Decisões devem ser tomadas com lógica e imparcialidade.",
    meaning_rev: "Unfairness, lack of accountability, dishonesty. Legal complications or injustice.",
    meaning_rev_pt: "Injustiça, falta de responsabilidade, desonestidade. Complicações legais ou injustiça.",
    description: "A figure sits between pillars, holding scales in one hand and a sword in the other, representing balanced judgment and swift action.",
    love: "Fairness in relationships. Karma plays a role - treat others as you wish to be treated.",
    career: "Legal matters may arise. Act with integrity. Fair dealing leads to success.",
    advice: "Be honest with yourself and others. Take responsibility for your actions, for every cause has its effect.",
    imageUrl: `${IMG_BASE}/ar11.jpg`
  },
  {
    id: "maj_12",
    name: "The Hanged Man",
    name_pt: "O Enforcado",
    number: 12,
    arcana: "major",
    element: "Water",
    keywords: ["Surrender", "New Perspective", "Letting Go", "Sacrifice"],
    keywords_pt: ["Rendição", "Nova Perspectiva", "Deixar Ir", "Sacrifício"],
    meaning_up: "Pause, surrender, letting go, new perspectives. Sometimes you must release control to gain insight.",
    meaning_up_pt: "Pausa, rendição, deixar ir, novas perspectivas. Às vezes você deve liberar o controle para ganhar insight.",
    meaning_rev: "Stalling, resistance, indecision. Refusing to see things differently.",
    meaning_rev_pt: "Estagnação, resistência, indecisão. Recusar ver as coisas de forma diferente.",
    description: "A man hangs upside down from a T-shaped cross, his face serene despite his position. A halo surrounds his head, suggesting enlightenment through surrender.",
    love: "Let go of expectations. A new perspective on relationships brings clarity.",
    career: "Pause and reassess. Sacrifice may be needed for future gains. Don't force progress.",
    advice: "Sometimes the best action is inaction. Surrender your need for control and see your situation from a new angle.",
    imageUrl: `${IMG_BASE}/ar12.jpg`
  },
  {
    id: "maj_13",
    name: "Death",
    name_pt: "A Morte",
    number: 13,
    arcana: "major",
    element: "Water",
    keywords: ["Endings", "Transformation", "Transition", "Release"],
    keywords_pt: ["Finais", "Transformação", "Transição", "Liberação"],
    meaning_up: "Endings, major change, transformation, transition. One chapter closes so another can begin.",
    meaning_up_pt: "Finais, grande mudança, transformação, transição. Um capítulo se fecha para que outro possa começar.",
    meaning_rev: "Resistance to change, stagnation, fear of endings. Refusing to let go of the past.",
    meaning_rev_pt: "Resistência à mudança, estagnação, medo de finais. Recusar deixar o passado ir.",
    description: "A skeletal figure on horseback carries a black flag with a white flower. People of all stations - king, maiden, child - fall before him, showing that transformation spares no one.",
    love: "End of a relationship phase - not necessarily the relationship itself. Transformation brings renewal.",
    career: "Major career change or ending. Don't resist - transformation leads to new opportunities.",
    advice: "Embrace endings as necessary for new beginnings. What dies makes room for what's being born.",
    imageUrl: `${IMG_BASE}/ar13.jpg`
  },
  {
    id: "maj_14",
    name: "Temperance",
    name_pt: "A Temperança",
    number: 14,
    arcana: "major",
    element: "Fire",
    keywords: ["Balance", "Moderation", "Patience", "Harmony"],
    keywords_pt: ["Equilíbrio", "Moderação", "Paciência", "Harmonia"],
    meaning_up: "Balance, moderation, patience, purpose. Finding the middle ground and bringing harmony to opposites.",
    meaning_up_pt: "Equilíbrio, moderação, paciência, propósito. Encontrar o meio-termo e trazer harmonia aos opostos.",
    meaning_rev: "Imbalance, excess, lack of long-term vision. Going to extremes.",
    meaning_rev_pt: "Desequilíbrio, excesso, falta de visão de longo prazo. Ir aos extremos.",
    description: "An angel pours water between two cups, representing the flow between conscious and subconscious. One foot rests on land, one in water, showing balance between realms.",
    love: "Balance in relationships. Patience and moderation lead to harmony. Blend differences with grace.",
    career: "Find balance in work-life. Take a measured approach. Patience brings lasting success.",
    advice: "Practice moderation in all things. Blend opposing forces within you to find your true path.",
    imageUrl: `${IMG_BASE}/ar14.jpg`
  },
  {
    id: "maj_15",
    name: "The Devil",
    name_pt: "O Diabo",
    number: 15,
    arcana: "major",
    element: "Earth",
    keywords: ["Shadow Self", "Attachment", "Addiction", "Materialism"],
    keywords_pt: ["Sombra", "Apego", "Vício", "Materialismo"],
    meaning_up: "Bondage, addiction, materialism, shadow self. Facing the chains that bind you - often of your own making.",
    meaning_up_pt: "Escravidão, vício, materialismo, lado sombrio. Enfrentar as correntes que o prendem - frequentemente de sua própria criação.",
    meaning_rev: "Breaking free, releasing limiting beliefs, reclaiming power. Liberation from bondage.",
    meaning_rev_pt: "Libertar-se, soltar crenças limitantes, recuperar poder. Libertação da escravidão.",
    description: "A horned figure sits above two chained humans - but their chains are loose enough to remove. The imagery suggests bondage is often voluntary.",
    love: "Unhealthy attachments or patterns in love. Face your shadows to find freedom.",
    career: "Feeling trapped or enslaved to work. Examine what truly binds you.",
    advice: "Recognize the chains you've placed on yourself. You have more freedom than you believe - if you choose to take it.",
    imageUrl: `${IMG_BASE}/ar15.jpg`
  },
  {
    id: "maj_16",
    name: "The Tower",
    name_pt: "A Torre",
    number: 16,
    arcana: "major",
    element: "Fire",
    keywords: ["Sudden Change", "Upheaval", "Revelation", "Awakening"],
    keywords_pt: ["Mudança Súbita", "Ruptura", "Revelação", "Despertar"],
    meaning_up: "Sudden change, upheaval, chaos, revelation. Structures built on false foundations must fall.",
    meaning_up_pt: "Mudança súbita, ruptura, caos, revelação. Estruturas construídas em fundações falsas devem cair.",
    meaning_rev: "Fear of change, avoiding disaster, delaying the inevitable. Building on unstable ground.",
    meaning_rev_pt: "Medo de mudança, evitar desastre, adiar o inevitável. Construir em terreno instável.",
    description: "Lightning strikes a tower, knocking off its crown. Figures fall from the structure as flames engulf it - yet in destruction, truth is revealed.",
    love: "Sudden revelation or upheaval in relationships. What wasn't working becomes clear.",
    career: "Unexpected disruption at work. Though shocking, it clears the way for rebuilding better.",
    advice: "Sometimes things must fall apart before they can come together correctly. Trust that destruction leads to liberation.",
    imageUrl: `${IMG_BASE}/ar16.jpg`
  },
  {
    id: "maj_17",
    name: "The Star",
    name_pt: "A Estrela",
    number: 17,
    arcana: "major",
    element: "Air",
    keywords: ["Hope", "Faith", "Renewal", "Serenity"],
    keywords_pt: ["Esperança", "Fé", "Renovação", "Serenidade"],
    meaning_up: "Hope, faith, purpose, renewal. After the storm comes calm. Healing and serenity are at hand.",
    meaning_up_pt: "Esperança, fé, propósito, renovação. Depois da tempestade vem a calma. Cura e serenidade estão à mão.",
    meaning_rev: "Lack of faith, despair, disconnection. Losing hope or spiritual connection.",
    meaning_rev_pt: "Falta de fé, desespero, desconexão. Perder esperança ou conexão espiritual.",
    description: "A naked woman kneels by a pool, pouring water onto land and sea. Above her shines one large star surrounded by seven smaller ones, representing hope and inspiration.",
    love: "Renewed hope in love. Healing from past hurts. Soul connections and spiritual love.",
    career: "Follow your star - your true calling. Inspiration leads the way. Creative success.",
    advice: "Have faith. After hardship comes renewal. You are guided by a light that never goes out.",
    imageUrl: `${IMG_BASE}/ar17.jpg`
  },
  {
    id: "maj_18",
    name: "The Moon",
    name_pt: "A Lua",
    number: 18,
    arcana: "major",
    element: "Water",
    keywords: ["Illusion", "Fear", "Intuition", "Subconscious"],
    keywords_pt: ["Ilusão", "Medo", "Intuição", "Subconsciente"],
    meaning_up: "Illusion, fear, anxiety, subconscious. Things are not as they seem. Navigate by intuition through uncertain times.",
    meaning_up_pt: "Ilusão, medo, ansiedade, subconsciente. As coisas não são o que parecem. Navegue pela intuição em tempos incertos.",
    meaning_rev: "Release of fear, truth revealed, overcoming anxiety. The fog begins to lift.",
    meaning_rev_pt: "Libertação do medo, verdade revelada, superação da ansiedade. A névoa começa a se dissipar.",
    description: "A moon with a mysterious face shines over a path leading between two towers. A dog and wolf howl at it while a crayfish emerges from the water - symbols of the wild and civilized mind.",
    love: "Confusion or deception in love. Trust your instincts. All is not as it appears.",
    career: "Uncertainty and illusion at work. Look beneath the surface before making decisions.",
    advice: "In times of uncertainty, trust your intuition over your fears. The path through darkness requires inner light.",
    imageUrl: `${IMG_BASE}/ar18.jpg`
  },
  {
    id: "maj_19",
    name: "The Sun",
    name_pt: "O Sol",
    number: 19,
    arcana: "major",
    element: "Fire",
    keywords: ["Joy", "Success", "Vitality", "Positivity"],
    keywords_pt: ["Alegria", "Sucesso", "Vitalidade", "Positividade"],
    meaning_up: "Success, vitality, joy, positivity. The warmth of the sun touches all. A time of abundance and celebration.",
    meaning_up_pt: "Sucesso, vitalidade, alegria, positividade. O calor do sol toca a todos. Um tempo de abundância e celebração.",
    meaning_rev: "Temporary sadness, lack of success, dimmed joy. The sun hidden behind clouds.",
    meaning_rev_pt: "Tristeza temporária, falta de sucesso, alegria diminuída. O sol escondido atrás das nuvens.",
    description: "A radiant sun shines over a joyful child on a white horse. Sunflowers bloom in the background, turning their faces to the light.",
    love: "Joy and happiness in love. Warmth, vitality, and positive energy in relationships.",
    career: "Success and recognition at work. Your efforts bear fruit. Shine brightly.",
    advice: "Embrace the light and warmth available to you. Joy is your birthright - let yourself shine.",
    imageUrl: `${IMG_BASE}/ar19.jpg`
  },
  {
    id: "maj_20",
    name: "Judgement",
    name_pt: "O Julgamento",
    number: 20,
    arcana: "major",
    element: "Fire",
    keywords: ["Rebirth", "Inner Calling", "Absolution", "Awakening"],
    keywords_pt: ["Renascimento", "Chamado Interior", "Absolvição", "Despertar"],
    meaning_up: "Judgement, rebirth, inner calling, absolution. A higher calling awakens you. Time for evaluation and renewal.",
    meaning_up_pt: "Julgamento, renascimento, chamado interior, absolvição. Um chamado superior o desperta. Hora de avaliação e renovação.",
    meaning_rev: "Self-doubt, refusal of self-examination, ignoring the call. Fear of judgment.",
    meaning_rev_pt: "Auto-dúvida, recusa de auto-exame, ignorar o chamado. Medo do julgamento.",
    description: "An angel blows a trumpet as the dead rise from their graves, arms outstretched in spiritual awakening. A new day of reckoning has arrived.",
    love: "Reevaluate your relationships. A call to deeper commitment or necessary endings.",
    career: "A calling to your true vocation. Career transformation through self-reflection.",
    advice: "Answer the call to become who you're meant to be. It's time to rise up and embrace your purpose.",
    imageUrl: `${IMG_BASE}/ar20.jpg`
  },
  {
    id: "maj_21",
    name: "The World",
    name_pt: "O Mundo",
    number: 21,
    arcana: "major",
    element: "Earth",
    keywords: ["Completion", "Integration", "Accomplishment", "Travel"],
    keywords_pt: ["Completude", "Integração", "Realização", "Viagem"],
    meaning_up: "Completion, integration, accomplishment, travel. A cycle completes. Achievement and wholeness are at hand.",
    meaning_up_pt: "Completude, integração, realização, viagem. Um ciclo se completa. Conquista e plenitude estão à mão.",
    meaning_rev: "Lack of completion, lack of closure. Seeking shortcuts or feeling incomplete.",
    meaning_rev_pt: "Falta de completude, falta de encerramento. Buscar atalhos ou sentir-se incompleto.",
    description: "A dancing figure is surrounded by a laurel wreath, with the four fixed signs of the zodiac in the corners. All elements unite in celebration of wholeness.",
    love: "Fulfillment in love. A complete and whole relationship. Celebration of union.",
    career: "Achievement and success. Goals reached. Time to celebrate before the next cycle.",
    advice: "Celebrate your accomplishments - you've come full circle. Honor the completion before beginning anew.",
    imageUrl: `${IMG_BASE}/ar21.jpg`
  },

  // ========== MINOR ARCANA - WANDS ==========
  {
    id: "min_wands_1",
    name: "Ace of Wands",
    name_pt: "Ás de Paus",
    number: 1,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Inspiration", "New Opportunity", "Growth", "Potential"],
    keywords_pt: ["Inspiração", "Nova Oportunidade", "Crescimento", "Potencial"],
    meaning_up: "New creative beginning, inspiration, growth potential. A spark of enthusiasm ignites new possibilities.",
    meaning_up_pt: "Novo começo criativo, inspiração, potencial de crescimento. Uma faísca de entusiasmo acende novas possibilidades.",
    meaning_rev: "Delays, lack of motivation, creative blocks. The spark fails to catch.",
    meaning_rev_pt: "Atrasos, falta de motivação, bloqueios criativos. A faísca não pega.",
    description: "A hand emerges from a cloud holding a flowering wand. Leaves fall from it, suggesting new growth and fertile opportunities.",
    love: "A new passionate romance or renewed spark in existing relationships.",
    career: "New creative projects or business ventures. Take inspired action.",
    advice: "Seize this moment of inspiration. The universe offers you a gift of potential - act on it.",
    imageUrl: `${IMG_BASE}/wa.jpg`
  },
  {
    id: "min_wands_2",
    name: "Two of Wands",
    name_pt: "Dois de Paus",
    number: 2,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Planning", "Progress", "Decisions", "Discovery"],
    keywords_pt: ["Planejamento", "Progresso", "Decisões", "Descoberta"],
    meaning_up: "Future planning, progress, decisions, discovery. You hold the world in your hands - plan your next move.",
    meaning_up_pt: "Planejamento futuro, progresso, decisões, descoberta. Você segura o mundo nas mãos - planeje seu próximo passo.",
    meaning_rev: "Fear of the unknown, lack of planning, being stuck. Refusing to step forward.",
    meaning_rev_pt: "Medo do desconhecido, falta de planejamento, estar preso. Recusar dar o próximo passo.",
    description: "A figure stands on castle walls, holding a globe in one hand and a wand in the other, gazing out at the world with plans unfolding.",
    love: "Planning for the future of your relationship. Consider your long-term compatibility.",
    career: "Strategic planning leads to expansion. Think big and plan accordingly.",
    advice: "You've achieved some success - now plan the next phase. Don't rest on your laurels.",
    imageUrl: `${IMG_BASE}/wa02.jpg`
  },
  {
    id: "min_wands_3",
    name: "Three of Wands",
    name_pt: "Três de Paus",
    number: 3,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Expansion", "Foresight", "Overseas", "Leadership"],
    keywords_pt: ["Expansão", "Previsão", "Exterior", "Liderança"],
    meaning_up: "Expansion, foresight, overseas opportunities. Your ships are coming in. The future looks bright.",
    meaning_up_pt: "Expansão, previsão, oportunidades no exterior. Seus navios estão chegando. O futuro parece brilhante.",
    meaning_rev: "Obstacles to long-term plans, delays in travel or expansion. Frustration with progress.",
    meaning_rev_pt: "Obstáculos a planos de longo prazo, atrasos em viagens ou expansão. Frustração com o progresso.",
    description: "A figure stands on a cliff watching ships sail across the sea, representing ventures sent out into the world now returning with reward.",
    love: "Long-distance love or travel together. Expansion of your romantic horizons.",
    career: "International opportunities. Expansion of business. Leadership roles emerge.",
    advice: "Your efforts are bearing fruit. Keep watching the horizon - more success approaches.",
    imageUrl: `${IMG_BASE}/wa03.jpg`
  },
  {
    id: "min_wands_4",
    name: "Four of Wands",
    name_pt: "Quatro de Paus",
    number: 4,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Celebration", "Harmony", "Milestone", "Home"],
    keywords_pt: ["Celebração", "Harmonia", "Marco", "Lar"],
    meaning_up: "Celebration, harmony, milestones, homecoming. A time of joy and community celebration.",
    meaning_up_pt: "Celebração, harmonia, marcos, volta ao lar. Um tempo de alegria e celebração comunitária.",
    meaning_rev: "Lack of harmony, cancelled celebrations, feeling unwelcome. Instability at home.",
    meaning_rev_pt: "Falta de harmonia, celebrações canceladas, sentir-se indesejado. Instabilidade no lar.",
    description: "Four wands form a canopy decorated with flowers, under which people dance in celebration. A castle stands welcomingly in the background.",
    love: "Engagement, wedding, or celebration of love. Domestic happiness.",
    career: "Team success, work celebrations, achieving milestones together.",
    advice: "Celebrate your achievements with those who helped you get there. Joy is meant to be shared.",
    imageUrl: `${IMG_BASE}/wa04.jpg`
  },
  {
    id: "min_wands_5",
    name: "Five of Wands",
    name_pt: "Cinco de Paus",
    number: 5,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Competition", "Conflict", "Tension", "Diversity"],
    keywords_pt: ["Competição", "Conflito", "Tensão", "Diversidade"],
    meaning_up: "Competition, rivalry, conflict, diversity of opinion. Creative tension that can spark growth.",
    meaning_up_pt: "Competição, rivalidade, conflito, diversidade de opinião. Tensão criativa que pode gerar crescimento.",
    meaning_rev: "Avoiding conflict, respecting differences, compromise. Or escalating unnecessary battles.",
    meaning_rev_pt: "Evitar conflito, respeitar diferenças, compromisso. Ou escalar batalhas desnecessárias.",
    description: "Five youths each brandish a wand, seemingly in conflict but perhaps just in spirited competition or debate.",
    love: "Arguments and disagreements in love. Healthy debate or unhealthy conflict.",
    career: "Workplace competition. Defend your ideas but stay open to others.",
    advice: "Some conflict is necessary for growth. Engage constructively and don't back down from healthy competition.",
    imageUrl: `${IMG_BASE}/wa05.jpg`
  },
  {
    id: "min_wands_6",
    name: "Six of Wands",
    name_pt: "Seis de Paus",
    number: 6,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Victory", "Recognition", "Progress", "Self-Confidence"],
    keywords_pt: ["Vitória", "Reconhecimento", "Progresso", "Autoconfiança"],
    meaning_up: "Victory, public recognition, progress, self-confidence. You've won and others acknowledge it.",
    meaning_up_pt: "Vitória, reconhecimento público, progresso, autoconfiança. Você venceu e outros reconhecem isso.",
    meaning_rev: "Excess pride, lack of recognition, private achievement. Victory without acknowledgment.",
    meaning_rev_pt: "Excesso de orgulho, falta de reconhecimento, conquista privada. Vitória sem reconhecimento.",
    description: "A figure rides triumphantly through a crowd, wearing a laurel wreath and carrying a wand topped with another wreath of victory.",
    love: "Success in love brings confidence. Others admire your relationship.",
    career: "Public recognition, promotion, or award. Enjoy your moment of triumph.",
    advice: "Accept recognition gracefully. You've earned this victory - let yourself be celebrated.",
    imageUrl: `${IMG_BASE}/wa06.jpg`
  },
  {
    id: "min_wands_7",
    name: "Seven of Wands",
    name_pt: "Sete de Paus",
    number: 7,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Challenge", "Defense", "Perseverance", "Standing Ground"],
    keywords_pt: ["Desafio", "Defesa", "Perseverança", "Manter Posição"],
    meaning_up: "Challenge, defense, perseverance. Standing your ground against opposition. You have the advantage.",
    meaning_up_pt: "Desafio, defesa, perseverança. Manter sua posição contra oposição. Você tem a vantagem.",
    meaning_rev: "Feeling overwhelmed, giving up, being protective. Losing ground or surrendering.",
    meaning_rev_pt: "Sentir-se sobrecarregado, desistir, ser protetor. Perder terreno ou se render.",
    description: "A figure stands on higher ground, defending against six wands rising from below. Despite being outnumbered, position gives advantage.",
    love: "Defend your relationship from outside interference. Stand firm in your values.",
    career: "Defend your position at work. Competition is fierce but you can prevail.",
    advice: "Don't back down from challenges. You have the high ground - use it to your advantage.",
    imageUrl: `${IMG_BASE}/wa07.jpg`
  },
  {
    id: "min_wands_8",
    name: "Eight of Wands",
    name_pt: "Oito de Paus",
    number: 8,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Speed", "Action", "Movement", "Quick Decisions"],
    keywords_pt: ["Velocidade", "Ação", "Movimento", "Decisões Rápidas"],
    meaning_up: "Swift action, movement, quick decisions, air travel. Things are moving fast - keep up.",
    meaning_up_pt: "Ação rápida, movimento, decisões rápidas, viagem aérea. As coisas estão se movendo rápido - acompanhe.",
    meaning_rev: "Delays, frustration, waiting, obstacles to progress. Momentum slowing.",
    meaning_rev_pt: "Atrasos, frustração, espera, obstáculos ao progresso. Momentum diminuindo.",
    description: "Eight wands fly through the air over a landscape, suggesting rapid movement and swift transmission of energy or messages.",
    love: "Rapid developments in love. Messages, travel together, or fast-paced romance.",
    career: "Fast progress on projects. News arrives quickly. Act decisively.",
    advice: "The time for waiting is over - things are moving rapidly. Be ready to act and adapt.",
    imageUrl: `${IMG_BASE}/wa08.jpg`
  },
  {
    id: "min_wands_9",
    name: "Nine of Wands",
    name_pt: "Nove de Paus",
    number: 9,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Resilience", "Courage", "Persistence", "Boundaries"],
    keywords_pt: ["Resiliência", "Coragem", "Persistência", "Limites"],
    meaning_up: "Resilience, courage, persistence, test of faith. You're battle-worn but still standing.",
    meaning_up_pt: "Resiliência, coragem, persistência, teste de fé. Você está marcado pela batalha mas ainda de pé.",
    meaning_rev: "Paranoia, defensiveness, giving up before the finish. Exhaustion from fighting.",
    meaning_rev_pt: "Paranoia, defensividade, desistir antes do fim. Exaustão de tanto lutar.",
    description: "A wounded figure leans on a wand for support, eight more wands forming a fence behind. Despite weariness, vigilance remains.",
    love: "Past hurts make you defensive. Protect yourself but don't close off entirely.",
    career: "Near the finish line - don't give up now. Rest but remain vigilant.",
    advice: "You've been through a lot, but the end is near. Gather your remaining strength for one final push.",
    imageUrl: `${IMG_BASE}/wa09.jpg`
  },
  {
    id: "min_wands_10",
    name: "Ten of Wands",
    name_pt: "Dez de Paus",
    number: 10,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Burden", "Responsibility", "Hard Work", "Stress"],
    keywords_pt: ["Fardo", "Responsabilidade", "Trabalho Duro", "Estresse"],
    meaning_up: "Burden, extra responsibility, hard work, stress. You've taken on too much but the goal is in sight.",
    meaning_up_pt: "Fardo, responsabilidade extra, trabalho duro, estresse. Você assumiu demais mas o objetivo está à vista.",
    meaning_rev: "Inability to delegate, burnout, releasing burdens. Learning to share the load.",
    meaning_rev_pt: "Incapacidade de delegar, esgotamento, liberar fardos. Aprender a dividir a carga.",
    description: "A figure struggles to carry ten heavy wands toward a town in the distance. The burden is great but the destination is visible.",
    love: "Relationship feels like work. Distribute responsibilities more fairly.",
    career: "Overworked and overburdened. Delegate or prioritize before burning out.",
    advice: "You don't have to carry everything alone. Delegate, prioritize, or set some burdens down.",
    imageUrl: `${IMG_BASE}/wa10.jpg`
  },
  {
    id: "min_wands_11",
    name: "Page of Wands",
    name_pt: "Pajem de Paus",
    number: 11,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Exploration", "Excitement", "Freedom", "Discovery"],
    keywords_pt: ["Exploração", "Entusiasmo", "Liberdade", "Descoberta"],
    meaning_up: "Exploration, excitement, freedom, discovery. A message of inspiration or a new creative venture.",
    meaning_up_pt: "Exploração, entusiasmo, liberdade, descoberta. Uma mensagem de inspiração ou novo empreendimento criativo.",
    meaning_rev: "Lack of direction, procrastination, creating drama. Scattered energy.",
    meaning_rev_pt: "Falta de direção, procrastinação, criar drama. Energia dispersa.",
    description: "A young figure studies their wand with curiosity and enthusiasm, ready for adventure but still learning.",
    love: "New exciting romance or playful energy in love. Be open to adventure.",
    career: "New project or creative idea. Enthusiasm and curiosity drive exploration.",
    advice: "Follow your curiosity with enthusiasm. This is a time for exploration and discovery.",
    imageUrl: `${IMG_BASE}/wapa.jpg`
  },
  {
    id: "min_wands_12",
    name: "Knight of Wands",
    name_pt: "Cavaleiro de Paus",
    number: 12,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Action", "Adventure", "Passion", "Impulsiveness"],
    keywords_pt: ["Ação", "Aventura", "Paixão", "Impulsividade"],
    meaning_up: "Action, adventure, passion, impulsiveness. Charging forward with energy and enthusiasm.",
    meaning_up_pt: "Ação, aventura, paixão, impulsividade. Avançar com energia e entusiasmo.",
    meaning_rev: "Haste, scattered energy, delays, frustration. Action without direction.",
    meaning_rev_pt: "Pressa, energia dispersa, atrasos, frustração. Ação sem direção.",
    description: "A knight charges forward on horseback, wand raised, dressed in armor decorated with salamanders - creatures of fire.",
    love: "Passionate but possibly short-lived romance. Excitement and adventure in love.",
    career: "Bold action leads to progress. Take risks but have some plan.",
    advice: "Channel your passion into purposeful action. Be bold but don't let impulsiveness lead you astray.",
    imageUrl: `${IMG_BASE}/wakn.jpg`
  },
  {
    id: "min_wands_13",
    name: "Queen of Wands",
    name_pt: "Rainha de Paus",
    number: 13,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Courage", "Confidence", "Independence", "Warmth"],
    keywords_pt: ["Coragem", "Confiança", "Independência", "Calor"],
    meaning_up: "Courage, confidence, independence, social butterfly. A warm, vibrant person who inspires others.",
    meaning_up_pt: "Coragem, confiança, independência, borboleta social. Uma pessoa calorosa e vibrante que inspira outros.",
    meaning_rev: "Jealousy, selfishness, demanding, overbearing. Fire that burns rather than warms.",
    meaning_rev_pt: "Ciúme, egoísmo, exigente, dominador. Fogo que queima em vez de aquecer.",
    description: "A confident queen sits on her throne, holding a wand and sunflower. A black cat at her feet represents her connection to the mysterious.",
    love: "Confident, passionate love. Either you embody this energy or seek someone who does.",
    career: "Leadership through charisma and vision. Inspire others with your passion.",
    advice: "Own your power and warmth. Your confidence and enthusiasm are contagious - use them wisely.",
    imageUrl: `${IMG_BASE}/waqu.jpg`
  },
  {
    id: "min_wands_14",
    name: "King of Wands",
    name_pt: "Rei de Paus",
    number: 14,
    arcana: "minor",
    suit: "Wands",
    element: "Fire",
    keywords: ["Vision", "Entrepreneur", "Honor", "Leadership"],
    keywords_pt: ["Visão", "Empreendedor", "Honra", "Liderança"],
    meaning_up: "Natural-born leader, vision, entrepreneur, honor. Leadership through inspiration rather than control.",
    meaning_up_pt: "Líder nato, visão, empreendedor, honra. Liderança através de inspiração em vez de controle.",
    meaning_rev: "Impulsiveness, haste, ruthless, high expectations. Leadership becoming tyranny.",
    meaning_rev_pt: "Impulsividade, pressa, implacável, altas expectativas. Liderança se tornando tirania.",
    description: "A king sits on his throne decorated with lions and salamanders, holding a flowering wand. He embodies mature creative leadership.",
    love: "Passionate, generous partner. Natural leader in relationships.",
    career: "Entrepreneurial success. Lead with vision and inspire your team.",
    advice: "Lead with vision and integrity. Your fire inspires others - make sure it lights the way, not burns bridges.",
    imageUrl: `${IMG_BASE}/waki.jpg`
  },

  // ========== MINOR ARCANA - CUPS ==========
  {
    id: "min_cups_1",
    name: "Ace of Cups",
    name_pt: "Ás de Copas",
    number: 1,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["New Love", "Compassion", "Creativity", "Intuition"],
    keywords_pt: ["Novo Amor", "Compaixão", "Criatividade", "Intuição"],
    meaning_up: "New relationships, compassion, creativity, emotional awakening. The cup of love overflows.",
    meaning_up_pt: "Novos relacionamentos, compaixão, criatividade, despertar emocional. O cálice do amor transborda.",
    meaning_rev: "Self-love needed, blocked emotions, emptiness. The cup is empty or overturned.",
    meaning_rev_pt: "Amor próprio necessário, emoções bloqueadas, vazio. O cálice está vazio ou virado.",
    description: "A hand extends from a cloud, offering a golden cup overflowing with streams of water. A dove descends toward it.",
    love: "New love enters your life or existing love deepens. Open your heart.",
    career: "Creative inspiration. Work that fulfills emotionally. New emotional beginnings.",
    advice: "Your heart is open and ready to receive. Accept the gift of emotional abundance being offered.",
    imageUrl: `${IMG_BASE}/cua.jpg`
  },
  {
    id: "min_cups_2",
    name: "Two of Cups",
    name_pt: "Dois de Copas",
    number: 2,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Unity", "Partnership", "Connection", "Attraction"],
    keywords_pt: ["União", "Parceria", "Conexão", "Atração"],
    meaning_up: "Unified love, partnership, attraction, connection. Two souls meet in harmony.",
    meaning_up_pt: "Amor unificado, parceria, atração, conexão. Duas almas se encontram em harmonia.",
    meaning_rev: "Imbalance, broken communication, tension. Partnership out of harmony.",
    meaning_rev_pt: "Desequilíbrio, comunicação quebrada, tensão. Parceria fora de harmonia.",
    description: "Two figures stand facing each other, exchanging cups in a pledge of mutual connection. A caduceus rises between them.",
    love: "Deep romantic connection. Soul mate energy. Partnership and mutual respect.",
    career: "Beneficial business partnerships. Collaboration leads to success.",
    advice: "Honor the connections in your life. True partnership is built on mutual respect and exchange.",
    imageUrl: `${IMG_BASE}/cu02.jpg`
  },
  {
    id: "min_cups_3",
    name: "Three of Cups",
    name_pt: "Três de Copas",
    number: 3,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Celebration", "Friendship", "Creativity", "Community"],
    keywords_pt: ["Celebração", "Amizade", "Criatividade", "Comunidade"],
    meaning_up: "Celebration, friendship, creativity, community. Time to celebrate with your tribe.",
    meaning_up_pt: "Celebração, amizade, criatividade, comunidade. Hora de celebrar com sua tribo.",
    meaning_rev: "Overindulgence, gossip, isolation. Celebration turning sour.",
    meaning_rev_pt: "Excesso, fofoca, isolamento. Celebração azedando.",
    description: "Three women dance together, raising their cups in celebration. Fruits and flowers surround them in abundance.",
    love: "Joyful social connections. Celebrating love with community. Group activities.",
    career: "Team success worth celebrating. Creative collaboration thrives.",
    advice: "Celebrate your blessings with those who matter. Joy multiplies when shared.",
    imageUrl: `${IMG_BASE}/cu03.jpg`
  },
  {
    id: "min_cups_4",
    name: "Four of Cups",
    name_pt: "Quatro de Copas",
    number: 4,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Meditation", "Contemplation", "Apathy", "Reevaluation"],
    keywords_pt: ["Meditação", "Contemplação", "Apatia", "Reavaliação"],
    meaning_up: "Meditation, contemplation, apathy, reevaluation. Turning inward, perhaps missing opportunities.",
    meaning_up_pt: "Meditação, contemplação, apatia, reavaliação. Voltando-se para dentro, talvez perdendo oportunidades.",
    meaning_rev: "Sudden awareness, new perspective, acceptance. Finally seeing what was offered.",
    meaning_rev_pt: "Consciência súbita, nova perspectiva, aceitação. Finalmente vendo o que foi oferecido.",
    description: "A figure sits under a tree, arms crossed, three cups before them while a fourth is offered by a hand from a cloud - unnoticed.",
    love: "Emotional withdrawal or taking love for granted. Look at what's being offered.",
    career: "Boredom or apathy at work. New opportunity may be missed if you don't look up.",
    advice: "Look around you - opportunities are being offered that you may be ignoring. Come out of your contemplation.",
    imageUrl: `${IMG_BASE}/cu04.jpg`
  },
  {
    id: "min_cups_5",
    name: "Five of Cups",
    name_pt: "Cinco de Copas",
    number: 5,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Loss", "Grief", "Regret", "Disappointment"],
    keywords_pt: ["Perda", "Luto", "Arrependimento", "Decepção"],
    meaning_up: "Loss, grief, disappointment, regret. Focusing on what's lost rather than what remains.",
    meaning_up_pt: "Perda, luto, decepção, arrependimento. Focar no que foi perdido em vez do que resta.",
    meaning_rev: "Acceptance, moving on, finding peace. Beginning to see the cups still standing.",
    meaning_rev_pt: "Aceitação, seguir em frente, encontrar paz. Começando a ver os cálices ainda de pé.",
    description: "A cloaked figure mourns over three spilled cups, not noticing the two cups still standing behind them, nor the bridge to a new life.",
    love: "Grieving a relationship or loss. Don't let sorrow blind you to remaining possibilities.",
    career: "Setback or disappointment at work. Process the loss but don't dwell too long.",
    advice: "Grieve what needs grieving, but remember - two cups still stand. Turn around and see what remains.",
    imageUrl: `${IMG_BASE}/cu05.jpg`
  },
  {
    id: "min_cups_6",
    name: "Six of Cups",
    name_pt: "Seis de Copas",
    number: 6,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Nostalgia", "Childhood", "Innocence", "Reunion"],
    keywords_pt: ["Nostalgia", "Infância", "Inocência", "Reencontro"],
    meaning_up: "Nostalgia, childhood memories, innocence, reunion. The sweetness of the past.",
    meaning_up_pt: "Nostalgia, memórias de infância, inocência, reencontro. A doçura do passado.",
    meaning_rev: "Stuck in the past, naive, unrealistic. Living in memories rather than the present.",
    meaning_rev_pt: "Preso no passado, ingênuo, irrealista. Vivendo em memórias em vez do presente.",
    description: "A child offers a cup filled with flowers to a smaller child. Old houses and five other cups surround them in a scene of innocent giving.",
    love: "Reconnection with past love or childhood sweetheart. Sweet, innocent love.",
    career: "Past connections bring opportunity. Nostalgia for simpler work times.",
    advice: "Honor your past and let it inform your present, but don't get lost in it. Sweet memories are gifts, not destinations.",
    imageUrl: `${IMG_BASE}/cu06.jpg`
  },
  {
    id: "min_cups_7",
    name: "Seven of Cups",
    name_pt: "Sete de Copas",
    number: 7,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Fantasy", "Illusion", "Choices", "Wishful Thinking"],
    keywords_pt: ["Fantasia", "Ilusão", "Escolhas", "Pensamento Desejoso"],
    meaning_up: "Fantasy, illusion, choices, wishful thinking. Many options but which are real?",
    meaning_up_pt: "Fantasia, ilusão, escolhas, pensamento desejoso. Muitas opções mas quais são reais?",
    meaning_rev: "Clarity, focus, realistic choices. Illusions dispelled.",
    meaning_rev_pt: "Clareza, foco, escolhas realistas. Ilusões dissipadas.",
    description: "A silhouette faces seven cups floating in clouds, each containing a different fantastical vision - wealth, beauty, a snake, a castle, jewels, a wreath, a dragon.",
    love: "Fantasy vs reality in love. Are you seeing your partner clearly?",
    career: "Many options but careful evaluation needed. Don't chase illusions.",
    advice: "Dreams and fantasies have their place, but discernment is needed now. Which cups contain real treasures?",
    imageUrl: `${IMG_BASE}/cu07.jpg`
  },
  {
    id: "min_cups_8",
    name: "Eight of Cups",
    name_pt: "Oito de Copas",
    number: 8,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Departure", "Withdrawal", "Searching", "Deeper Meaning"],
    keywords_pt: ["Partida", "Retirada", "Busca", "Significado Mais Profundo"],
    meaning_up: "Walking away, disappointment, searching for deeper meaning. Leaving behind what no longer serves.",
    meaning_up_pt: "Partir, decepção, buscar significado mais profundo. Deixar para trás o que não serve mais.",
    meaning_rev: "Fear of change, stagnation, staying in unfulfilling situations. Afraid to walk away.",
    meaning_rev_pt: "Medo de mudança, estagnação, permanecer em situações insatisfatórias. Medo de partir.",
    description: "A cloaked figure walks away from eight neatly stacked cups, heading toward mountains under a moon. Something is missing despite apparent abundance.",
    love: "Walking away from a relationship that lacks depth. Seeking more meaningful connection.",
    career: "Leaving a job that no longer fulfills. Searching for more meaningful work.",
    advice: "Sometimes we must leave behind what looks good on paper to find what feeds the soul. Trust your instinct to move on.",
    imageUrl: `${IMG_BASE}/cu08.jpg`
  },
  {
    id: "min_cups_9",
    name: "Nine of Cups",
    name_pt: "Nove de Copas",
    number: 9,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Satisfaction", "Wishes Fulfilled", "Comfort", "Contentment"],
    keywords_pt: ["Satisfação", "Desejos Realizados", "Conforto", "Contentamento"],
    meaning_up: "Wishes fulfilled, satisfaction, contentment, emotional stability. The wish card.",
    meaning_up_pt: "Desejos realizados, satisfação, contentamento, estabilidade emocional. A carta do desejo.",
    meaning_rev: "Greed, dissatisfaction, materialism. Having everything but feeling empty.",
    meaning_rev_pt: "Ganância, insatisfação, materialismo. Ter tudo mas sentir-se vazio.",
    description: "A satisfied figure sits before nine golden cups arranged in an arc, arms crossed in contentment. Wishes have come true.",
    love: "Emotional fulfillment in love. Wishes for romance coming true.",
    career: "Career satisfaction and accomplishment. Enjoying the fruits of your labor.",
    advice: "Your wishes are manifesting. Enjoy this time of fulfillment and be grateful for your blessings.",
    imageUrl: `${IMG_BASE}/cu09.jpg`
  },
  {
    id: "min_cups_10",
    name: "Ten of Cups",
    name_pt: "Dez de Copas",
    number: 10,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Harmony", "Marriage", "Happiness", "Alignment"],
    keywords_pt: ["Harmonia", "Casamento", "Felicidade", "Alinhamento"],
    meaning_up: "Divine love, blissful relationships, harmony, alignment. The happily ever after.",
    meaning_up_pt: "Amor divino, relacionamentos abençoados, harmonia, alinhamento. O felizes para sempre.",
    meaning_rev: "Broken family, misalignment of values, domestic trouble. Paradise lost.",
    meaning_rev_pt: "Família quebrada, desalinhamento de valores, problemas domésticos. Paraíso perdido.",
    description: "A couple embraces while children dance nearby. A rainbow of ten cups arches over a beautiful home. Family bliss achieved.",
    love: "Lasting love and domestic happiness. Family harmony and deep fulfillment.",
    career: "Work-life balance achieved. Career supports rather than hinders family happiness.",
    advice: "This is what fulfillment looks like. Cherish and protect the harmony you've created.",
    imageUrl: `${IMG_BASE}/cu10.jpg`
  },
  {
    id: "min_cups_11",
    name: "Page of Cups",
    name_pt: "Pajem de Copas",
    number: 11,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Creative Opportunity", "Intuition", "Curiosity", "Messages"],
    keywords_pt: ["Oportunidade Criativa", "Intuição", "Curiosidade", "Mensagens"],
    meaning_up: "Creative opportunities, intuitive messages, curiosity, emotional exploration.",
    meaning_up_pt: "Oportunidades criativas, mensagens intuitivas, curiosidade, exploração emocional.",
    meaning_rev: "Emotional immaturity, creative blocks, disappointing news. Naivety in love.",
    meaning_rev_pt: "Imaturidade emocional, bloqueios criativos, notícias decepcionantes. Ingenuidade no amor.",
    description: "A young figure gazes curiously at a fish emerging from their cup, representing unexpected messages from the emotional/subconscious realm.",
    love: "Sweet, innocent romance beginning. Messages of love. Youthful emotional expression.",
    career: "Creative opportunity arises. Trust your intuition in projects.",
    advice: "Stay open to messages from your intuition. Approach emotions with curiosity rather than fear.",
    imageUrl: `${IMG_BASE}/cupa.jpg`
  },
  {
    id: "min_cups_12",
    name: "Knight of Cups",
    name_pt: "Cavaleiro de Copas",
    number: 12,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Romance", "Charm", "Imagination", "Beauty"],
    keywords_pt: ["Romance", "Charme", "Imaginação", "Beleza"],
    meaning_up: "Romance, charm, imagination, following the heart. The romantic knight arrives.",
    meaning_up_pt: "Romance, charme, imaginação, seguir o coração. O cavaleiro romântico chega.",
    meaning_rev: "Moodiness, unrealistic, jealousy, disappointment. Romance without substance.",
    meaning_rev_pt: "Mau humor, irrealista, ciúme, decepção. Romance sem substância.",
    description: "A knight in armor decorated with fish rides slowly forward, carefully holding a cup. He follows his heart rather than charging into battle.",
    love: "Romantic proposals or declarations. Someone charming enters your life.",
    career: "Creative projects advance. Follow your passion with grace.",
    advice: "Follow your heart with grace and intention. Let romance and beauty guide your path.",
    imageUrl: `${IMG_BASE}/cukn.jpg`
  },
  {
    id: "min_cups_13",
    name: "Queen of Cups",
    name_pt: "Rainha de Copas",
    number: 13,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Compassion", "Nurturing", "Intuition", "Calm"],
    keywords_pt: ["Compaixão", "Nutrição", "Intuição", "Calma"],
    meaning_up: "Compassionate, caring, emotionally stable, intuitive, nurturing.",
    meaning_up_pt: "Compassiva, carinhosa, emocionalmente estável, intuitiva, nutritiva.",
    meaning_rev: "Co-dependency, emotional insecurity, martyrdom. Giving too much of yourself.",
    meaning_rev_pt: "Co-dependência, insegurança emocional, martírio. Dar demais de si mesmo.",
    description: "A serene queen sits on her throne at the edge of the sea, holding an ornate cup. She is at home in the realm of emotions.",
    love: "Deep emotional intelligence in relationships. Nurturing, compassionate love.",
    career: "Trust intuition in work decisions. Create emotionally supportive environments.",
    advice: "Trust your deep emotional wisdom. Nurture others from a place of fullness, not depletion.",
    imageUrl: `${IMG_BASE}/cuqu.jpg`
  },
  {
    id: "min_cups_14",
    name: "King of Cups",
    name_pt: "Rei de Copas",
    number: 14,
    arcana: "minor",
    suit: "Cups",
    element: "Water",
    keywords: ["Emotional Balance", "Diplomacy", "Compassion", "Control"],
    keywords_pt: ["Equilíbrio Emocional", "Diplomacia", "Compaixão", "Controle"],
    meaning_up: "Emotionally balanced, diplomatic, compassionate. Mastery over emotions without suppression.",
    meaning_up_pt: "Emocionalmente equilibrado, diplomático, compassivo. Domínio sobre emoções sem supressão.",
    meaning_rev: "Emotional manipulation, moodiness, volatility. Emotions ruling rather than serving.",
    meaning_rev_pt: "Manipulação emocional, mau humor, volatilidade. Emoções dominando em vez de servir.",
    description: "A king sits on a throne amid turbulent seas, yet remains calm. A fish pendant and ship represent his mastery of emotional depths.",
    love: "Mature, emotionally intelligent partnership. A partner who handles emotions with grace.",
    career: "Lead with emotional intelligence. Diplomacy and compassion bring success.",
    advice: "Master your emotions without suppressing them. True strength is feeling deeply while remaining balanced.",
    imageUrl: `${IMG_BASE}/cuki.jpg`
  },

  // ========== MINOR ARCANA - SWORDS ==========
  {
    id: "min_swords_1",
    name: "Ace of Swords",
    name_pt: "Ás de Espadas",
    number: 1,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Clarity", "Truth", "Breakthrough", "New Ideas"],
    keywords_pt: ["Clareza", "Verdade", "Avanço", "Novas Ideias"],
    meaning_up: "Mental clarity, truth, breakthrough, new ideas. A sword of truth cuts through confusion.",
    meaning_up_pt: "Clareza mental, verdade, avanço, novas ideias. Uma espada da verdade corta através da confusão.",
    meaning_rev: "Confusion, chaos, miscommunication. Truth obscured or weaponized.",
    meaning_rev_pt: "Confusão, caos, má comunicação. Verdade obscurecida ou usada como arma.",
    description: "A hand emerges from a cloud grasping an upright sword, crowned with a wreath of victory and olive branch of peace.",
    love: "Clarity about relationships. Truth must be spoken. Cut through confusion.",
    career: "Mental breakthrough at work. New idea cuts through obstacles.",
    advice: "The truth will set you free - wield it wisely. Mental clarity is available if you're willing to see clearly.",
    imageUrl: `${IMG_BASE}/swa.jpg`
  },
  {
    id: "min_swords_2",
    name: "Two of Swords",
    name_pt: "Dois de Espadas",
    number: 2,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Indecision", "Stalemate", "Blocked Emotions", "Avoidance"],
    keywords_pt: ["Indecisão", "Impasse", "Emoções Bloqueadas", "Evitação"],
    meaning_up: "Difficult decisions, stalemate, avoidance, blocked emotions. Refusing to see.",
    meaning_up_pt: "Decisões difíceis, impasse, evitação, emoções bloqueadas. Recusar ver.",
    meaning_rev: "Indecision, information overload, no right choice. Or finally facing the truth.",
    meaning_rev_pt: "Indecisão, sobrecarga de informação, sem escolha certa. Ou finalmente enfrentar a verdade.",
    description: "A blindfolded figure holds two crossed swords in perfect balance, the sea churning behind them. A decision must be made but is being avoided.",
    love: "Avoiding difficult conversations in love. Stalemate in relationship decisions.",
    career: "At a crossroads - decision needed. Stop avoiding the choice.",
    advice: "Remove the blindfold. You have the information you need - the time for avoidance is over.",
    imageUrl: `${IMG_BASE}/sw02.jpg`
  },
  {
    id: "min_swords_3",
    name: "Three of Swords",
    name_pt: "Três de Espadas",
    number: 3,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Heartbreak", "Sorrow", "Grief", "Separation"],
    keywords_pt: ["Coração Partido", "Tristeza", "Luto", "Separação"],
    meaning_up: "Heartbreak, emotional pain, sorrow, grief. The pain that teaches.",
    meaning_up_pt: "Coração partido, dor emocional, tristeza, luto. A dor que ensina.",
    meaning_rev: "Recovery, forgiveness, moving on. The worst pain is passing.",
    meaning_rev_pt: "Recuperação, perdão, seguir em frente. A pior dor está passando.",
    description: "Three swords pierce a heart against a stormy sky. The pain is real and present but the storm will pass.",
    love: "Heartbreak, betrayal, or painful separation. Allow yourself to grieve.",
    career: "Painful work situation - rejection, criticism, or loss. Process the hurt.",
    advice: "Feel this pain fully rather than avoiding it. Healing begins with acknowledgment.",
    imageUrl: `${IMG_BASE}/sw03.jpg`
  },
  {
    id: "min_swords_4",
    name: "Four of Swords",
    name_pt: "Quatro de Espadas",
    number: 4,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Rest", "Recovery", "Contemplation", "Relaxation"],
    keywords_pt: ["Descanso", "Recuperação", "Contemplação", "Relaxamento"],
    meaning_up: "Rest, relaxation, meditation, recovery. A necessary pause for healing.",
    meaning_up_pt: "Descanso, relaxamento, meditação, recuperação. Uma pausa necessária para cura.",
    meaning_rev: "Restlessness, burnout, stagnation. Refusing needed rest or staying too long in retreat.",
    meaning_rev_pt: "Inquietação, esgotamento, estagnação. Recusar descanso necessário ou ficar muito tempo em retiro.",
    description: "A figure lies in repose on a tomb, hands folded in prayer. Three swords hang above while one lies beneath - a time of necessary stillness.",
    love: "Take a break from relationship stress. Heal before engaging again.",
    career: "Rest and recover from work stress. Don't push - recuperation is productive.",
    advice: "Rest is not weakness - it's wisdom. Retreat, recover, and emerge renewed.",
    imageUrl: `${IMG_BASE}/sw04.jpg`
  },
  {
    id: "min_swords_5",
    name: "Five of Swords",
    name_pt: "Cinco de Espadas",
    number: 5,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Conflict", "Defeat", "Winning at All Costs", "Loss"],
    keywords_pt: ["Conflito", "Derrota", "Vencer a Qualquer Custo", "Perda"],
    meaning_up: "Conflict, defeat, walking away, winning but at what cost? Pyrrhic victory.",
    meaning_up_pt: "Conflito, derrota, ir embora, vencer mas a que custo? Vitória de Pirro.",
    meaning_rev: "Reconciliation, making amends, moving past conflict. Choosing peace.",
    meaning_rev_pt: "Reconciliação, fazer as pazes, superar conflito. Escolher a paz.",
    description: "A figure smirks while holding three swords, two more at their feet. Defeated opponents walk away. But is this really winning?",
    love: "Arguments where no one wins. Pride damages relationships.",
    career: "Workplace conflict - choose battles wisely. Some fights aren't worth winning.",
    advice: "Ask yourself: is winning this battle worth losing the war? Sometimes walking away is the real victory.",
    imageUrl: `${IMG_BASE}/sw05.jpg`
  },
  {
    id: "min_swords_6",
    name: "Six of Swords",
    name_pt: "Seis de Espadas",
    number: 6,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Transition", "Change", "Moving On", "Rite of Passage"],
    keywords_pt: ["Transição", "Mudança", "Seguir em Frente", "Rito de Passagem"],
    meaning_up: "Transition, change, moving on, travel. Moving toward calmer waters.",
    meaning_up_pt: "Transição, mudança, seguir em frente, viagem. Movendo-se para águas mais calmas.",
    meaning_rev: "Unable to move on, resistance, unfinished business. Stuck between old and new.",
    meaning_rev_pt: "Incapaz de seguir em frente, resistência, assuntos inacabados. Preso entre velho e novo.",
    description: "A ferryman guides a boat carrying a woman and child from choppy waters toward calmer seas. Six swords stand in the boat - the baggage they carry.",
    love: "Moving on from difficult relationship dynamics. Traveling toward better times.",
    career: "Career transition. Leaving difficulties behind for better opportunities.",
    advice: "You can't stay where you are. Though you carry wounds, you're moving toward peace.",
    imageUrl: `${IMG_BASE}/sw06.jpg`
  },
  {
    id: "min_swords_7",
    name: "Seven of Swords",
    name_pt: "Sete de Espadas",
    number: 7,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Deception", "Strategy", "Sneakiness", "Getting Away"],
    keywords_pt: ["Engano", "Estratégia", "Furtividade", "Escapar"],
    meaning_up: "Deception, trickery, strategy, getting away with something. Not everything is above board.",
    meaning_up_pt: "Engano, trapaça, estratégia, sair impune de algo. Nem tudo está às claras.",
    meaning_rev: "Coming clean, rethinking approach, getting caught. Truth emerging.",
    meaning_rev_pt: "Confessar, repensar abordagem, ser pego. Verdade emergindo.",
    description: "A figure sneaks away from a camp carrying five swords, leaving two behind. Looking over their shoulder, they seem to be getting away with something.",
    love: "Deception or secrets in relationships. Trust may be broken.",
    career: "Strategic maneuvering at work. Someone may not be honest.",
    advice: "Be careful of deception - from others or yourself. Sometimes cunning is needed, but consider the cost.",
    imageUrl: `${IMG_BASE}/sw07.jpg`
  },
  {
    id: "min_swords_8",
    name: "Eight of Swords",
    name_pt: "Oito de Espadas",
    number: 8,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Restriction", "Imprisonment", "Self-Imposed Limitations", "Victim Mentality"],
    keywords_pt: ["Restrição", "Aprisionamento", "Limitações Auto-Impostas", "Mentalidade de Vítima"],
    meaning_up: "Restriction, imprisonment, powerlessness, but mostly self-imposed. The cage has no lock.",
    meaning_up_pt: "Restrição, aprisionamento, impotência, mas principalmente auto-imposta. A jaula não tem fechadura.",
    meaning_rev: "Self-acceptance, new perspective, freedom. Seeing that the bindings are loose.",
    meaning_rev_pt: "Auto-aceitação, nova perspectiva, liberdade. Ver que as amarras estão soltas.",
    description: "A blindfolded, bound figure stands surrounded by eight swords. But look closely - the bindings are loose, the swords don't touch them.",
    love: "Feeling trapped in relationship but the prison is mental. You have more power than you think.",
    career: "Feeling stuck at work but options exist. Remove your blindfold.",
    advice: "The barriers that bind you are largely of your own making. You can walk away any time you choose to see clearly.",
    imageUrl: `${IMG_BASE}/sw08.jpg`
  },
  {
    id: "min_swords_9",
    name: "Nine of Swords",
    name_pt: "Nove de Espadas",
    number: 9,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Anxiety", "Worry", "Fear", "Nightmares"],
    keywords_pt: ["Ansiedade", "Preocupação", "Medo", "Pesadelos"],
    meaning_up: "Anxiety, worry, fear, nightmares. The dark night of the soul - often worse in imagination than reality.",
    meaning_up_pt: "Ansiedade, preocupação, medo, pesadelos. A noite escura da alma - frequentemente pior na imaginação do que na realidade.",
    meaning_rev: "Hope, reaching out, slowly recovering. The night is ending.",
    meaning_rev_pt: "Esperança, buscar ajuda, recuperando-se lentamente. A noite está terminando.",
    description: "A figure sits up in bed, head in hands, nine swords hanging on the wall behind. The quilted blanket shows both roses and astrological symbols - beauty and meaning exist even in dark times.",
    love: "Anxiety about relationships keeping you up at night. Talk about your fears.",
    career: "Work worries dominating thoughts. Anxiety may be worse than reality.",
    advice: "Your fears feel overwhelming, but the night always ends. Reach out for support - you don't have to face this alone.",
    imageUrl: `${IMG_BASE}/sw09.jpg`
  },
  {
    id: "min_swords_10",
    name: "Ten of Swords",
    name_pt: "Dez de Espadas",
    number: 10,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Ending", "Betrayal", "Rock Bottom", "Inevitable End"],
    keywords_pt: ["Fim", "Traição", "Fundo do Poço", "Fim Inevitável"],
    meaning_up: "Painful ending, betrayal, rock bottom, defeat. But also: it can't get worse than this.",
    meaning_up_pt: "Fim doloroso, traição, fundo do poço, derrota. Mas também: não pode ficar pior que isso.",
    meaning_rev: "Recovery, regeneration, resisting an inevitable end. Dawn approaches.",
    meaning_rev_pt: "Recuperação, regeneração, resistir a um fim inevitável. O amanhecer se aproxima.",
    description: "A figure lies face down, ten swords in their back. But look - the sky shows dawn breaking. This ending precedes a new beginning.",
    love: "Painful ending of relationship. Complete heartbreak. But from this, renewal becomes possible.",
    career: "Career situation hits rock bottom. Total defeat. But this allows rebuilding.",
    advice: "This is the end - accept it. But notice the dawn in the sky. From this low point, the only way is up.",
    imageUrl: `${IMG_BASE}/sw10.jpg`
  },
  {
    id: "min_swords_11",
    name: "Page of Swords",
    name_pt: "Pajem de Espadas",
    number: 11,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Curiosity", "Mental Restlessness", "New Ideas", "Communication"],
    keywords_pt: ["Curiosidade", "Inquietação Mental", "Novas Ideias", "Comunicação"],
    meaning_up: "Curiosity, restlessness, mental energy, new ideas. Eager to learn and communicate.",
    meaning_up_pt: "Curiosidade, inquietação, energia mental, novas ideias. Ansioso para aprender e comunicar.",
    meaning_rev: "Scattered thinking, cynicism, gossip. Intellect without wisdom.",
    meaning_rev_pt: "Pensamento disperso, cinismo, fofoca. Intelecto sem sabedoria.",
    description: "A young figure holds a sword aloft, looking over their shoulder with alertness. Wind blows their hair as clouds swirl - mental activity is high.",
    love: "Curious about love but perhaps nervous or analytical. Open communication.",
    career: "New ideas and mental energy at work. Research and learning phase.",
    advice: "Your curiosity and mental energy are gifts. Channel them into focused learning rather than scattered thinking.",
    imageUrl: `${IMG_BASE}/swpa.jpg`
  },
  {
    id: "min_swords_12",
    name: "Knight of Swords",
    name_pt: "Cavaleiro de Espadas",
    number: 12,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Action", "Speed", "Ambition", "Assertiveness"],
    keywords_pt: ["Ação", "Velocidade", "Ambição", "Assertividade"],
    meaning_up: "Action, speed, ambition, driven. Charging forward with ideas and plans.",
    meaning_up_pt: "Ação, velocidade, ambição, determinação. Avançar com ideias e planos.",
    meaning_rev: "Impatience, impulsiveness, ruthlessness. Bulldozing without thinking.",
    meaning_rev_pt: "Impaciência, impulsividade, implacabilidade. Atropelar sem pensar.",
    description: "A knight charges forward on a white horse, sword raised, clouds swirling. The energy is unstoppable but perhaps reckless.",
    love: "Fast-moving romance or aggressive pursuit. Passion but possibly lacking depth.",
    career: "Aggressive action at work. Charging forward with plans. Be careful of collateral damage.",
    advice: "Your drive is powerful - use it wisely. Speed can be an asset, but don't lose sight of your target.",
    imageUrl: `${IMG_BASE}/swkn.jpg`
  },
  {
    id: "min_swords_13",
    name: "Queen of Swords",
    name_pt: "Rainha de Espadas",
    number: 13,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Independence", "Clear Thinking", "Direct Communication", "Boundaries"],
    keywords_pt: ["Independência", "Pensamento Claro", "Comunicação Direta", "Limites"],
    meaning_up: "Clear thinking, independence, direct communication, clear boundaries.",
    meaning_up_pt: "Pensamento claro, independência, comunicação direta, limites claros.",
    meaning_rev: "Coldness, cruelty, bitterness. Using intellect to wound.",
    meaning_rev_pt: "Frieza, crueldade, amargura. Usar intelecto para ferir.",
    description: "A queen sits on her throne, sword upright, one hand raised. Her face shows experience and wisdom earned through difficulty. Clouds gather but she is clear-headed.",
    love: "Direct communication in relationships. Setting clear boundaries. Independent love.",
    career: "Clear thinking cuts through work problems. Direct, honest leadership.",
    advice: "Speak your truth directly but with compassion. Your clarity is a gift - use it to heal, not harm.",
    imageUrl: `${IMG_BASE}/swqu.jpg`
  },
  {
    id: "min_swords_14",
    name: "King of Swords",
    name_pt: "Rei de Espadas",
    number: 14,
    arcana: "minor",
    suit: "Swords",
    element: "Air",
    keywords: ["Authority", "Truth", "Structure", "Intellect"],
    keywords_pt: ["Autoridade", "Verdade", "Estrutura", "Intelecto"],
    meaning_up: "Intellectual power, authority, truth, analytical. Mastery of mind and communication.",
    meaning_up_pt: "Poder intelectual, autoridade, verdade, analítico. Domínio da mente e comunicação.",
    meaning_rev: "Manipulation, cruelty, tyranny. Intellect used to dominate.",
    meaning_rev_pt: "Manipulação, crueldade, tirania. Intelecto usado para dominar.",
    description: "A king sits upright on his throne, sword raised, face stern but fair. He embodies the highest expression of mental mastery and just authority.",
    love: "Intellectual connection valued highly. Fair but perhaps emotionally detached.",
    career: "Leadership through expertise and clear thinking. Authority figure.",
    advice: "Lead with wisdom and fairness. Your mental clarity is a responsibility - use it to serve truth, not just yourself.",
    imageUrl: `${IMG_BASE}/swki.jpg`
  },

  // ========== MINOR ARCANA - PENTACLES ==========
  {
    id: "min_pentacles_1",
    name: "Ace of Pentacles",
    name_pt: "Ás de Ouros",
    number: 1,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Opportunity", "Prosperity", "New Venture", "Manifestation"],
    keywords_pt: ["Oportunidade", "Prosperidade", "Novo Empreendimento", "Manifestação"],
    meaning_up: "New financial opportunity, manifestation, prosperity. A seed of material abundance.",
    meaning_up_pt: "Nova oportunidade financeira, manifestação, prosperidade. Uma semente de abundância material.",
    meaning_rev: "Lost opportunity, lack of planning, scarcity mindset. Missed chances.",
    meaning_rev_pt: "Oportunidade perdida, falta de planejamento, mentalidade de escassez. Chances perdidas.",
    description: "A hand emerges from a cloud offering a golden pentacle. Below, a garden path leads through an archway to mountains - the path to material success.",
    love: "Stable, grounded new relationship. Building something real together.",
    career: "New job, business opportunity, or financial gain. Plant seeds for future success.",
    advice: "An opportunity for material success presents itself. Seize it and nurture it with practical action.",
    imageUrl: `${IMG_BASE}/pea.jpg`
  },
  {
    id: "min_pentacles_2",
    name: "Two of Pentacles",
    name_pt: "Dois de Ouros",
    number: 2,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Balance", "Adaptability", "Prioritization", "Time Management"],
    keywords_pt: ["Equilíbrio", "Adaptabilidade", "Priorização", "Gestão de Tempo"],
    meaning_up: "Balance, adaptability, time management, prioritization. Juggling multiple responsibilities.",
    meaning_up_pt: "Equilíbrio, adaptabilidade, gestão de tempo, priorização. Equilibrar múltiplas responsabilidades.",
    meaning_rev: "Overwhelm, disorganization, dropped balls. Too much to handle.",
    meaning_rev_pt: "Sobrecarga, desorganização, deixar cair bolas. Demais para lidar.",
    description: "A figure dances while juggling two pentacles connected by an infinity loop. Ships ride waves behind them - life is a constant balancing act.",
    love: "Balancing love with other life demands. Flexibility needed in relationships.",
    career: "Managing multiple work projects. Stay adaptable and keep priorities clear.",
    advice: "Life requires constant adjustment. Stay flexible, prioritize wisely, and enjoy the dance.",
    imageUrl: `${IMG_BASE}/pe02.jpg`
  },
  {
    id: "min_pentacles_3",
    name: "Three of Pentacles",
    name_pt: "Três de Ouros",
    number: 3,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Teamwork", "Collaboration", "Learning", "Implementation"],
    keywords_pt: ["Trabalho em Equipe", "Colaboração", "Aprendizado", "Implementação"],
    meaning_up: "Teamwork, collaboration, learning, skilled work. Building something great together.",
    meaning_up_pt: "Trabalho em equipe, colaboração, aprendizado, trabalho qualificado. Construir algo grandioso juntos.",
    meaning_rev: "Lack of teamwork, disregard for skills, poor quality. Working at cross purposes.",
    meaning_rev_pt: "Falta de trabalho em equipe, desconsiderar habilidades, baixa qualidade. Trabalhar com propósitos opostos.",
    description: "An artisan shows plans to two others in a cathedral. Each contributes their expertise - collaboration creates what no one could alone.",
    love: "Building something together in a relationship. Working as a team.",
    career: "Successful collaboration at work. Learning and applying skills. Recognition for expertise.",
    advice: "Great works are built through collaboration. Share your skills, learn from others, and build together.",
    imageUrl: `${IMG_BASE}/pe03.jpg`
  },
  {
    id: "min_pentacles_4",
    name: "Four of Pentacles",
    name_pt: "Quatro de Ouros",
    number: 4,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Security", "Control", "Conservation", "Possessiveness"],
    keywords_pt: ["Segurança", "Controle", "Conservação", "Possessividade"],
    meaning_up: "Security, control, conservatism, saving. Holding on tightly to what you have.",
    meaning_up_pt: "Segurança, controle, conservadorismo, economizar. Segurar firmemente o que você tem.",
    meaning_rev: "Generosity, releasing, spending freely, or alternatively - insecurity and greed.",
    meaning_rev_pt: "Generosidade, liberar, gastar livremente, ou alternativamente - insegurança e ganância.",
    description: "A figure sits rigidly, a pentacle on head, two under feet, one clutched to chest. They've got a grip on their resources but at what cost?",
    love: "Possessiveness or emotional guardedness. Fear of losing love.",
    career: "Financial security but perhaps at cost of growth. Holding on too tightly.",
    advice: "Security is important, but not at the cost of life itself. Know when to hold tight and when to let flow.",
    imageUrl: `${IMG_BASE}/pe04.jpg`
  },
  {
    id: "min_pentacles_5",
    name: "Five of Pentacles",
    name_pt: "Cinco de Ouros",
    number: 5,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Hardship", "Loss", "Isolation", "Worry"],
    keywords_pt: ["Dificuldade", "Perda", "Isolamento", "Preocupação"],
    meaning_up: "Financial hardship, poverty, isolation, worry. Hard times - but help may be closer than you think.",
    meaning_up_pt: "Dificuldade financeira, pobreza, isolamento, preocupação. Tempos difíceis - mas ajuda pode estar mais perto do que você pensa.",
    meaning_rev: "Recovery, end of hardship, spiritual poverty. Finding help or resources.",
    meaning_rev_pt: "Recuperação, fim da dificuldade, pobreza espiritual. Encontrar ajuda ou recursos.",
    description: "Two figures trudge through snow past a lit church window. They seem unaware that warmth and help are right there - if only they'd look up.",
    love: "Feeling left out in the cold in love. Isolation but support may be available.",
    career: "Financial difficulties or job loss. Hard times, but resources exist.",
    advice: "Times are hard, but don't let pride or despair blind you to available help. Look up - the light is closer than you think.",
    imageUrl: `${IMG_BASE}/pe05.jpg`
  },
  {
    id: "min_pentacles_6",
    name: "Six of Pentacles",
    name_pt: "Seis de Ouros",
    number: 6,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Generosity", "Charity", "Giving and Receiving", "Fairness"],
    keywords_pt: ["Generosidade", "Caridade", "Dar e Receber", "Equidade"],
    meaning_up: "Generosity, charity, giving and receiving, sharing wealth fairly.",
    meaning_up_pt: "Generosidade, caridade, dar e receber, compartilhar riqueza de forma justa.",
    meaning_rev: "Debt, selfishness, strings attached, one-sided giving.",
    meaning_rev_pt: "Dívida, egoísmo, condições ocultas, doação unilateral.",
    description: "A wealthy figure holds scales while giving coins to those in need. The transaction seems fair, though we might ask about the power dynamics.",
    love: "Balance of give and take in relationships. Generosity strengthens bonds.",
    career: "Receiving help or giving assistance at work. Fair transactions.",
    advice: "Generosity creates flow. Give when you can, receive with grace, and maintain balance in your exchanges.",
    imageUrl: `${IMG_BASE}/pe06.jpg`
  },
  {
    id: "min_pentacles_7",
    name: "Seven of Pentacles",
    name_pt: "Sete de Ouros",
    number: 7,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Assessment", "Investment", "Patience", "Long-Term View"],
    keywords_pt: ["Avaliação", "Investimento", "Paciência", "Visão de Longo Prazo"],
    meaning_up: "Assessment, patience, investment, long-term view. Pausing to evaluate what's growing.",
    meaning_up_pt: "Avaliação, paciência, investimento, visão de longo prazo. Pausar para avaliar o que está crescendo.",
    meaning_rev: "Impatience, not seeing results, bad investments. Frustration with slow growth.",
    meaning_rev_pt: "Impaciência, não ver resultados, maus investimentos. Frustração com crescimento lento.",
    description: "A figure leans on a hoe, gazing at seven pentacles growing on a bush. They've worked hard and now assess whether the growth is satisfactory.",
    love: "Evaluating whether relationship is growing in desired direction. Patience required.",
    career: "Assessing career progress and investments. Long-term view needed.",
    advice: "Step back and assess your progress. Growth takes time - are you investing in the right things?",
    imageUrl: `${IMG_BASE}/pe07.jpg`
  },
  {
    id: "min_pentacles_8",
    name: "Eight of Pentacles",
    name_pt: "Oito de Ouros",
    number: 8,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Apprenticeship", "Skill", "Dedication", "Diligence"],
    keywords_pt: ["Aprendizado", "Habilidade", "Dedicação", "Diligência"],
    meaning_up: "Dedication, skill development, hard work, apprenticeship. Mastering your craft.",
    meaning_up_pt: "Dedicação, desenvolvimento de habilidades, trabalho duro, aprendizado. Dominar seu ofício.",
    meaning_rev: "Perfectionism, no focus, lack of motivation. All work and no progress.",
    meaning_rev_pt: "Perfeccionismo, sem foco, falta de motivação. Todo trabalho e nenhum progresso.",
    description: "An artisan works intently on pentacles, focused on perfecting their craft. Six finished pentacles hang behind; the work continues.",
    love: "Working on relationship skills. Dedicated effort to improve love life.",
    career: "Skill development and dedication pay off. Focus on your craft.",
    advice: "Mastery comes through dedicated practice. Keep working on your skills - excellence is built one repetition at a time.",
    imageUrl: `${IMG_BASE}/pe08.jpg`
  },
  {
    id: "min_pentacles_9",
    name: "Nine of Pentacles",
    name_pt: "Nove de Ouros",
    number: 9,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Abundance", "Independence", "Self-Sufficiency", "Luxury"],
    keywords_pt: ["Abundância", "Independência", "Autossuficiência", "Luxo"],
    meaning_up: "Abundance, luxury, self-sufficiency, financial independence. Enjoying the fruits of your labor.",
    meaning_up_pt: "Abundância, luxo, autossuficiência, independência financeira. Desfrutar os frutos do seu trabalho.",
    meaning_rev: "Financial setbacks, overindulgence, lack of discipline. Prosperity threatened.",
    meaning_rev_pt: "Reveses financeiros, excesso, falta de disciplina. Prosperidade ameaçada.",
    description: "A well-dressed woman stands in a lush garden surrounded by grapevines heavy with fruit. A falcon rests on her gloved hand - she's achieved independence.",
    love: "Independence in love. Self-sufficient but open to partnership. Luxury and comfort.",
    career: "Financial success through your own efforts. Enjoying career achievements.",
    advice: "You've worked hard and earned this abundance. Enjoy it - but remember the discipline that got you here.",
    imageUrl: `${IMG_BASE}/pe09.jpg`
  },
  {
    id: "min_pentacles_10",
    name: "Ten of Pentacles",
    name_pt: "Dez de Ouros",
    number: 10,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Legacy", "Inheritance", "Family", "Long-Term Success"],
    keywords_pt: ["Legado", "Herança", "Família", "Sucesso de Longo Prazo"],
    meaning_up: "Legacy, inheritance, family wealth, long-term success. Wealth that spans generations.",
    meaning_up_pt: "Legado, herança, riqueza familiar, sucesso de longo prazo. Riqueza que atravessa gerações.",
    meaning_rev: "Family disputes, financial failure, loss of legacy. Wealth not passed on.",
    meaning_rev_pt: "Disputas familiares, fracasso financeiro, perda de legado. Riqueza não transmitida.",
    description: "An elderly figure sits at a grand archway, surrounded by family across generations. Ten pentacles are arranged in the Tree of Life pattern - complete material fulfillment.",
    love: "Family legacy, long-term stable relationship, building something lasting.",
    career: "Long-term financial security. Business success that creates lasting wealth.",
    advice: "Think beyond yourself - what legacy will you leave? Build something that lasts beyond your own lifetime.",
    imageUrl: `${IMG_BASE}/pe10.jpg`
  },
  {
    id: "min_pentacles_11",
    name: "Page of Pentacles",
    name_pt: "Pajem de Ouros",
    number: 11,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Ambition", "Study", "New Opportunity", "Manifestation"],
    keywords_pt: ["Ambição", "Estudo", "Nova Oportunidade", "Manifestação"],
    meaning_up: "New opportunities, ambition, desire to learn, manifestation beginning.",
    meaning_up_pt: "Novas oportunidades, ambição, desejo de aprender, manifestação começando.",
    meaning_rev: "Lack of progress, procrastination, missed opportunity. Dreams without action.",
    meaning_rev_pt: "Falta de progresso, procrastinação, oportunidade perdida. Sonhos sem ação.",
    description: "A young figure gazes intently at a pentacle held aloft, completely focused. A lush field surrounds them - potential waiting to be developed.",
    love: "New relationship with long-term potential. Building something real.",
    career: "New job opportunity or educational pursuit. Ambitious beginning.",
    advice: "Study your opportunities carefully. This is the seed stage - focus and dedication will help it grow.",
    imageUrl: `${IMG_BASE}/pepa.jpg`
  },
  {
    id: "min_pentacles_12",
    name: "Knight of Pentacles",
    name_pt: "Cavaleiro de Ouros",
    number: 12,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Efficiency", "Routine", "Responsibility", "Hard Work"],
    keywords_pt: ["Eficiência", "Rotina", "Responsabilidade", "Trabalho Duro"],
    meaning_up: "Hard work, efficiency, routine, conservatism. Slow and steady wins the race.",
    meaning_up_pt: "Trabalho duro, eficiência, rotina, conservadorismo. Devagar e sempre se ganha a corrida.",
    meaning_rev: "Boredom, laziness, stuck in routine, perfectionism blocking progress.",
    meaning_rev_pt: "Tédio, preguiça, preso na rotina, perfeccionismo bloqueando progresso.",
    description: "A knight sits motionless on a heavy workhorse, contemplating a pentacle. Unlike other knights, this one doesn't charge - methodical progress is their way.",
    love: "Steady, dependable partnership. Maybe lacking excitement but very reliable.",
    career: "Methodical progress at work. Reliability valued. Slow but sure advancement.",
    advice: "Consistency and reliability may not be glamorous, but they build lasting success. Keep showing up.",
    imageUrl: `${IMG_BASE}/pekn.jpg`
  },
  {
    id: "min_pentacles_13",
    name: "Queen of Pentacles",
    name_pt: "Rainha de Ouros",
    number: 13,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Nurturing", "Practical", "Financial Security", "Comfort"],
    keywords_pt: ["Nutritiva", "Prática", "Segurança Financeira", "Conforto"],
    meaning_up: "Nurturing, practical, providing, financially secure. Creating comfortable abundance.",
    meaning_up_pt: "Nutritiva, prática, provedora, financeiramente segura. Criar abundância confortável.",
    meaning_rev: "Imbalance between work and home, neglecting self-care, financial insecurity.",
    meaning_rev_pt: "Desequilíbrio entre trabalho e casa, negligenciar autocuidado, insegurança financeira.",
    description: "A queen sits on her throne in a flourishing garden, holding a pentacle in her lap. A rabbit represents fertility; she embodies practical nurturing.",
    love: "Nurturing, practical love. Creating a comfortable home together.",
    career: "Financial success while maintaining work-life balance. Practical prosperity.",
    advice: "True abundance includes both material comfort and time to enjoy it. Nurture yourself and others.",
    imageUrl: `${IMG_BASE}/pequ.jpg`
  },
  {
    id: "min_pentacles_14",
    name: "King of Pentacles",
    name_pt: "Rei de Ouros",
    number: 14,
    arcana: "minor",
    suit: "Pentacles",
    element: "Earth",
    keywords: ["Wealth", "Business", "Leadership", "Abundance"],
    keywords_pt: ["Riqueza", "Negócios", "Liderança", "Abundância"],
    meaning_up: "Wealth, security, business success, discipline. Material mastery achieved.",
    meaning_up_pt: "Riqueza, segurança, sucesso nos negócios, disciplina. Domínio material alcançado.",
    meaning_rev: "Materialism, greed, financial loss, poor business decisions.",
    meaning_rev_pt: "Materialismo, ganância, perda financeira, más decisões de negócios.",
    description: "A king sits on a throne decorated with bulls, surrounded by lush gardens and his castle. Grapevines and pentacles surround him - the ultimate material success.",
    love: "Stable, prosperous partnership. Provider energy. Material comfort in love.",
    career: "Height of career success. Business mastery. Leadership through proven results.",
    advice: "You've achieved material mastery. Use your resources wisely and generously - wealth is a tool, not an end.",
    imageUrl: `${IMG_BASE}/peki.jpg`
  }
];

// Helper function to get card by ID
export const getCardById = (id: string): TarotCardData | undefined => {
  return TAROT_CARDS.find(card => card.id === id);
};

// Helper function to get cards by arcana
export const getCardsByArcana = (arcana: 'major' | 'minor'): TarotCardData[] => {
  return TAROT_CARDS.filter(card => card.arcana === arcana);
};

// Helper function to get cards by suit
export const getCardsBySuit = (suit: string): TarotCardData[] => {
  return TAROT_CARDS.filter(card => card.suit === suit);
};

// Helper function to get random cards
export const getRandomCards = (count: number): TarotCardData[] => {
  const shuffled = [...TAROT_CARDS].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
};

export default TAROT_CARDS;
